SYMBOLS = [
    'BTCUSDT', 'ETHUSDT', 'BCHUSDT', 'XRPUSDT', 'EOSUSDT',
    'LTCUSDT', 'TRXUSDT', 'ETCUSDT', 'LINKUSDT', 'XLMUSDT',
    'ADAUSDT', 'XMRUSDT', 'DASHUSDT', 'ZECUSDT', 'XTZUSDT',
    'ATOMUSDT', 'BNBUSDT', 'ONTUSDT', 'IOTAUSDT', 'BATUSDT'
]

INTERVAL = '15m'
START_DATE = '1 June, 2025'
DATA_PATH = 'DataAnalysis/data/raw/'

ADF_SIGNIFICANCE_LEVEL = 0.1

COPULA_TYPE = 'STUDENT'
SEED = 42
N_OBS = 5000

REFERENCE_ASSET = 'BTCUSDT'
ENTRY_THRESHOLD = 0.20
EXIT_THRESHOLD = 0.10

USE_API_KEY = False
API_KEY = 'fck_me'
API_SECRET = 'fck_me_jesus'
