from enum import Enum


class CopulaType(Enum):
    GAUSSIAN = "gaussian"
    STUDENT  = "student"
    FRANK = "frank"
    JOE = "joe"
    AMH = "amh"
    CLAYTON = "clayton"
    FGM = "fgm"
    GALAMBOS = "galambos"
    GUMBEL = "gumbel"
    PLACKETT = "plackett"
    TAWN = "tawn"
    TAWNT1 = "tawnT1"
    TAWNT2 = "tawnT2"
    BB1 = "BB1"
    BB2 = "BB2"
    BB3 = "BB3"
    BB4 = "BB4"
    BB5 = "BB5"
    BB6 = "BB6"
    BB7 = "BB7"
    BB8 = "BB8"