[tool.black]
line-length = 100

[tool.pytest.ini_options]
addopts = "--cov=CopulaFurtif --cov-report=term-missing"
testpaths = ["tests"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"